### ISSUE TITLE
NullPointerException when trying to create launch configuration

### ISSUE THREAD

**Issue by sithmein** [jbosstools/jbosstools-quarkus#123]
Using the Quarkus extension 4.17.0 for Eclipse (2020-12) I always get a NullPointerException when I try to create a launch configuration:

```
eclipse.buildId=4.18.0.I20201202-1800
java.version=11.0.9
java.vendor=Gentoo
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=de_DE
Framework arguments:  -product org.eclipse.epp.package.java.product
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.java.product

org.eclipse.ui
Error
Wed Jan 13 17:50:25 CET 2021
An internal error has occurred.

java.lang.NullPointerException
	at org.jboss.tools.quarkus.core.launch.LaunchUtils.initializeQuarkusLaunchConfiguration(LaunchUtils.java:36)
	at org.jboss.tools.quarkus.ui.launch.QuarkusProjectTab.performApply(QuarkusProjectTab.java:112)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationTabGroupViewer.refresh(LaunchConfigurationTabGroupViewer.java:520)
	at org.eclipse.debug.internal.ui.launchConfigurations.LaunchConfigurationsDialog.updateButtons(LaunchConfigurationsDialog.java:1618)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTab.updateLaunchConfigurationDialog(AbstractLaunchConfigurationTab.java:155)
	at org.eclipse.debug.ui.AbstractLaunchConfigurationTab$1.runInUIThread(AbstractLaunchConfigurationTab.java:513)
...
```
After that the tab is not editable.

**Comment by jeffmaury** [comment]
Moved to https://issues.redhat.com/browse/JBIDE-27603
